# Generated by Django 4.0.4 on 2022-04-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_booking_action_remove_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='action',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
