# Generated by Django 4.0.4 on 2022-04-26 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_booking_action_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='action',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
