# Generated by Django 4.0.3 on 2022-04-07 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_caddress_client_ccountry_client_cdistrict_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='ccountry',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cdistrict',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cpincode',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cstate',
        ),
    ]
