# Generated by Django 4.0.3 on 2022-04-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_client_ccountry_remove_client_cdistrict_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ccountry',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='cstate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
