# Generated by Django 4.0.3 on 2022-04-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_client_ccountry_client_cstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cdistrict',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='cpincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
