# Generated by Django 4.0.3 on 2022-05-05 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
