# Generated by Django 4.0.3 on 2022-04-11 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmms', '0028_remove_service_acitive_alter_service_country'),
        ('client', '0008_alter_client_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_id', models.CharField(max_length=30)),
                ('verify', models.BooleanField(default=False)),
                ('pay_at', models.DateTimeField(auto_now_add=True)),
                ('clientdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmms.service')),
            ],
        ),
    ]
