# Generated by Django 4.0.3 on 2022-04-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_booking_address_booking_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pay_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
