# Generated by Django 4.0.3 on 2022-05-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='client',
        ),
    ]
