# Generated by Django 4.0.3 on 2022-04-12 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_alter_booking_pay_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='clientdetail',
            new_name='client',
        ),
    ]
