# Generated by Django 4.0.4 on 2022-04-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.FileField(default='avtar.png', upload_to='Profile_Pic'),
        ),
    ]
