# Generated by Django 4.0.4 on 2022-04-19 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_user_aadhar_user_aadharpic_user_address_user_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(blank=True, max_length=100, null=True)),
                ('typematerial', models.CharField(choices=[('Cement', 'Cement'), ('Plumbing', 'Plumbing'), ('Painting', 'Painting'), ('Furniture', 'Furniture'), ('TextTile', 'TextTile')], max_length=100)),
                ('country', models.CharField(blank=True, choices=[('India', 'India')], max_length=10, null=True)),
                ('state', models.CharField(blank=True, choices=[('Gujarat', 'Gujarat'), ('Goa', 'Goa'), ('Delhi', 'Delhi'), ('Rajsthan', 'Rajsthan')], max_length=10, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=100, null=True)),
                ('mname', models.CharField(blank=True, max_length=100, null=True)),
                ('mimage', models.FileField(blank=True, null=True, upload_to='materialimage')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('weights', models.IntegerField(blank=True, null=True)),
                ('nomc', models.IntegerField(blank=True, null=True)),
                ('proddesc', models.TextField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.user')),
            ],
        ),
    ]
