# Generated by Django 4.0.4 on 2022-04-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='acitive',
            field=models.BooleanField(default=True),
        ),
    ]
