# Generated by Django 4.0.4 on 2022-04-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_service_acitive'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='action',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
