# Generated by Django 4.0.4 on 2022-04-24 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_service_action_service_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='action',
        ),
        migrations.RemoveField(
            model_name='service',
            name='status',
        ),
    ]
