# Generated by Django 4.0.4 on 2022-04-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_remove_service_action_remove_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='action',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
