# Generated by Django 4.0.4 on 2022-04-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_service_action_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='act',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='sta',
            field=models.BooleanField(default=False),
        ),
    ]
