# Generated by Django 4.0.3 on 2022-03-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.FileField(default='avtar.png', upload_to='profile'),
        ),
    ]
