# Generated by Django 4.0.3 on 2022-03-31 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmms', '0002_user_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sector', models.CharField(choices=[('Cleaning', 'Cleaning'), ('AC', 'AC'), ('Car', 'Car')], max_length=100)),
                ('min_charge', models.IntegerField()),
                ('desc', models.TextField()),
                ('area', models.CharField(max_length=100)),
                ('acitive', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmms.user')),
            ],
        ),
    ]
