# Generated by Django 4.0.3 on 2022-03-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmms', '0003_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='sector',
            field=models.CharField(choices=[('Labour', 'Labour'), ('Material Transportation', 'Material Transportation'), ('Electrition', 'Electrition'), ('Plumber', 'Plumber')], max_length=100),
        ),
    ]
