# Generated by Django 4.0.3 on 2022-04-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmms', '0004_alter_service_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adddress',
            field=models.TextField(blank=True, null=True),
        ),
    ]
