# Generated by Django 4.0.3 on 2022-04-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmms', '0006_user_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
