# Generated by Django 4.0.3 on 2022-04-07 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmms', '0008_remove_user_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adddress',
        ),
    ]
