# Generated by Django 4.0.3 on 2022-04-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmms', '0009_remove_user_adddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='proof',
        ),
    ]
