# Generated by Django 4.0.3 on 2022-04-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmms', '0010_remove_user_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
