# Generated by Django 4.0.3 on 2022-04-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmms', '0012_user_district_user_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
