# Generated by Django 4.0.3 on 2022-04-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmms', '0015_alter_user_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='proof',
        ),
        migrations.AddField(
            model_name='user',
            name='aadharpic',
            field=models.FileField(blank=True, null=True, upload_to='AadharPic'),
        ),
    ]
