# Generated by Django 4.0.3 on 2022-04-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmms', '0016_remove_user_proof_user_aadharpic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='adddress',
            new_name='address',
        ),
    ]
