# Generated by Django 4.0.3 on 2022-04-08 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmms', '0017_rename_adddress_user_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='area',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='min_charge',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='desc',
            new_name='proddesc',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='shopname',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='sector',
            new_name='typematerial',
        ),
    ]
