# Generated by Django 4.0.3 on 2022-04-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmms', '0021_service_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='state',
            field=models.CharField(blank=True, choices=[('Gujarat', 'Gujarat'), ('Goa', 'Goa'), ('Delhi', 'Delhi'), ('Rajsthan', 'Rajsthan')], max_length=10, null=True),
        ),
    ]
