# Generated by Django 4.0.3 on 2022-04-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmms', '0022_service_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
