# Generated by Django 4.0.3 on 2022-04-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmms', '0024_service_mname_service_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='mimage',
            field=models.FileField(blank=True, null=True, upload_to='materialimage'),
        ),
    ]
