# Generated by Django 4.0.3 on 2022-04-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmms', '0027_service_nomc_service_weights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='acitive',
        ),
        migrations.AlterField(
            model_name='service',
            name='country',
            field=models.CharField(blank=True, choices=[('India', 'India')], max_length=10, null=True),
        ),
    ]
